repos:
    - repo: https://github.com/LiquidFun/aoc_tiles
      rev: 0.6.2
      hooks:
          - id: aoc-tiles
            args:
                - --contrast-improvement-type=dark
                - --show-total-stars-for-all-years=no
                - --overwrite-year=2024
                - --count-as-solved-when=on_leaderboard
